{
 "title": "Global Dashboard",
 "time": { "from": "now/y", "to": "now/y" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "track_or_stop",
    "label": "track_or_stop",
    "query": "select distinct track_or_stop from train;"
   }
  ]
 },
 "panels": [
  {
   "title": "Last postition for trains",
   "type": "geomap",
   "gridPos": { "h": 23, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "with foo as (\nselect\n\tmax(timestamps_utc) as time,\n\tmapped_veh_id\nfrom\n\ttrain t1\nwhere\n\t$__timeFilter(timestamps_utc)\ngroup by\n\tmapped_veh_id )\nselect\n\tmax(timestamps_utc) as time,\n\tmax(track_or_stop) as track_or_stop,\n\tavg(lat) as lat,\n\tavg(lon) as lon,\n\tt.mapped_veh_id\nfrom\n\ttrain t,\n\tfoo f\nwhere\n\tt.timestamps_utc = f.time\n\tand track_or_stop in ($track_or_stop)\n\tand f.mapped_veh_id = t.mapped_veh_id\n\tand track_or_stop = 1\nGROUP BY t.mapped_veh_id\norder by 1, 2, 3, 4"
    },
    {
     "rawSql": "with foo as (\nselect\n\tmax(timestamps_utc) as time,\n\tmapped_veh_id\nfrom\n\ttrain t1\nwhere\n\t$__timeFilter(timestamps_utc)\ngroup by\n\tmapped_veh_id )\nselect\n\tmax(timestamps_utc) as time,\n\tmax(track_or_stop) as track_or_stop,\n\tavg(lat) as lat,\n\tavg(lon) as lon,\n\tt.mapped_veh_id\nfrom\n\ttrain t,\n\tfoo f\nwhere\n\tt.timestamps_utc = f.time\n\tand track_or_stop in ($track_or_stop)\n\tand f.mapped_veh_id = t.mapped_veh_id\n\tand track_or_stop = 0\nGROUP BY t.mapped_veh_id\norder by 1, 2, 3, 4"
    }
   ]
  },
  {
   "title": "Total Number of Trains in Map & Table",
   "type": "stat",
   "description": "Measures the number of trains that have provided information during this time",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with foo as (\nselect\n\tmax(timestamps_utc) as time,\n  mapped_veh_id\nfrom\n\ttrain t1\nwhere\n\t$__timeFilter(timestamps_utc)\ngroup by\n\tmapped_veh_id ),\nfoo2 as (\n  select distinct f.mapped_veh_id from \n  foo f, train t\n  where f.time= t.timestamps_utc and f.mapped_veh_id = t.mapped_veh_id and t.track_or_stop in ($track_or_stop)\n) SELECT count(*) from foo2;"
    }
   ]
  },
  {
   "title": "Active",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with foo as (\nselect\n\tmax(timestamps_utc) as time,\n  mapped_veh_id\nfrom\n\ttrain t1\nwhere\n\t$__timeFilter(timestamps_utc)\ngroup by\n\tmapped_veh_id ),\nfoo2 as (\n  select distinct f.mapped_veh_id from \n  foo f, train t\n  where f.time= t.timestamps_utc and f.mapped_veh_id = t.mapped_veh_id and t.track_or_stop = 0\n) SELECT count(*) from foo2;"
    }
   ]
  },
  {
   "title": "Inactive",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with foo as (\nselect\n\tmax(timestamps_utc) as time,\n  mapped_veh_id\nfrom\n\ttrain t1\nwhere\n\t$__timeFilter(timestamps_utc)\ngroup by\n\tmapped_veh_id ),\nfoo2 as (\n  select distinct f.mapped_veh_id from \n  foo f, train t\n  where f.time= t.timestamps_utc and f.mapped_veh_id = t.mapped_veh_id and t.track_or_stop = 1\n) SELECT count(*) from foo2;"
    }
   ]
  },
  {
   "title": "Anomalies Detection",
   "type": "table",
   "description": "The anomalies idx is a variable that goes from 0 (no anomalies detected) to 3 (all anomalies detected)\n\nThe parking is a variable that measures if a train has stopped at a location. 0 is moving, and 1 is stopped \n\nOccurences measures the amount of data points you have in this time interval",
   "gridPos": { "h": 18, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT \n  mapped_veh_id as \"Id\",\n  avg(anomalies_triggered) as \"Anomalies idx\",\n  avg(track_or_stop) as \"Active\",\n  count(*) as Occurences\nfrom train \nwhere \n  $__timeFilter(timestamps_utc)\n  and track_or_stop in ($track_or_stop)\nGROUP BY mapped_veh_id\norder by 2 desc, 4 desc;"
    }
   ]
  }
 ]
}